// This file is automatically generated. Do not edit.
// If you want to switch to a different Firebase project, select it from the Firebase Studio menu.
import { initializeApp } from 'firebase/app';
import { firebaseConfig } from './firebase-config';

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export { app, firebaseConfig };
