// This file is automatically generated. Do not edit.
// If you want to switch to a different Firebase project, select it from the Firebase Studio menu.
export const firebaseConfig = {
  apiKey: "AIzaSyD0PAZ7dDze-R6mWHvPW9vFgAOowPVGmeQ",
  authDomain: "agentverse-srkp3.firebaseapp.com",
  projectId: "agentverse-srkp3",
  storageBucket: "agentverse-srkp3.firebasestorage.app",
  messagingSenderId: "971119613005",
  appId: "1:971119613005:web:28b354a0a43f048dc57804"
};
