"use client";

import { useState, useEffect } from 'react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from "@/hooks/use-toast"
import { generatePoemTitle } from '@/ai/flows/generate-poem-title';
import { providePoemInspirationInsights } from '@/ai/flows/provide-poem-inspiration-insights';
import { Clipboard, Download, Edit, Loader2, Save, Share2, Sparkles, Wand2 } from 'lucide-react';
import type { GeneratePoemFromImageOutput } from '@/ai/flows/generate-poem-from-image';
import type { PoemInspirationInsightsOutput } from '@/ai/flows/provide-poem-inspiration-insights';
import AiInsights from './AiInsights';
import PoemLine from './PoemLine';
import { useLibrary } from '@/context/LibraryContext';
import { useAuth } from '@/context/AuthContext';
import { PlaceHolderImages } from '@/lib/placeholder-images';

interface PoemDisplayProps {
  poemResult: GeneratePoemFromImageOutput;
  image: string;
}

export default function PoemDisplay({ poemResult, image }: PoemDisplayProps) {
  const [title, setTitle] = useState(poemResult.title);
  const [poem, setPoem] = useState(poemResult.poem);
  const [isEditing, setIsEditing] = useState(false);
  const [isTitleLoading, setIsTitleLoading] = useState(false);
  const [showInsights, setShowInsights] = useState(false);
  const [insights, setInsights] = useState<PoemInspirationInsightsOutput | null>(null);
  const [isInsightsLoading, setIsInsightsLoading] = useState(false);
  const { toast } = useToast();
  const { addPoemToLibrary } = useLibrary();
  const { user } = useAuth();


  useEffect(() => {
    setTitle(poemResult.title);
    setPoem(poemResult.poem);
  }, [poemResult]);

  const handleGenerateTitle = async () => {
    setIsTitleLoading(true);
    try {
      const { title: newTitle } = await generatePoemTitle({ poem });
      setTitle(newTitle);
      toast({ title: "New title generated!" });
    } catch (error) {
      toast({ title: "Error generating title", variant: 'destructive' });
    } finally {
      setIsTitleLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(`${title}\n\n${poem}`);
    toast({ title: "Poem copied to clipboard!" });
  };
  
  const handleShare = async () => {
    const shareData = {
      title: `Poem: ${title}`,
      text: `${title}\n\n${poem}\n\n- Generated by Versify`,
    };
    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        handleCopy();
      }
    } catch (err) {
      console.error('Share failed:', err);
      handleCopy();
    }
  };

  const handleDownload = () => {
    const blob = new Blob([`${title}\n\n${poem}`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Poem downloaded." });
  }

  const handleFetchInsights = async () => {
    setShowInsights(!showInsights);
    if (!insights && !showInsights) {
      setIsInsightsLoading(true);
      try {
        const insightsResult = await providePoemInspirationInsights({ photoDataUri: image, poem });
        setInsights(insightsResult);
      } catch (error) {
        toast({ title: "Could not get AI insights.", variant: 'destructive' });
      } finally {
        setIsInsightsLoading(false);
      }
    }
  };

  const updatePoemLine = (lineNumber: number, newText: string) => {
    const lines = poem.split('\n');
    lines[lineNumber] = newText;
    setPoem(lines.join('\n'));
  }
  
  const handleSave = () => {
    if (!user) {
        toast({ title: "Please log in to save poems.", variant: "destructive" });
        return;
    }
    const imagePlaceholder = PlaceHolderImages.find(p => p.imageUrl === image) || {
        id: `custom-${Date.now()}`,
        imageUrl: image,
        description: 'Custom uploaded image',
        imageHint: ''
    };
    addPoemToLibrary({ title, poem, image: imagePlaceholder });
    toast({ title: "Saved to your library!" });
  }

  return (
    <div className="flex flex-col lg:flex-row gap-6 lg:gap-8 h-full animate-in fade-in duration-500">
      <div className="relative lg:w-1/3 aspect-square lg:aspect-auto rounded-xl overflow-hidden shadow-md">
        <Image src={image} alt="Poem inspiration" layout="fill" objectFit="cover" />
      </div>

      <div className="lg:w-2/3 flex flex-col">
        <div className="flex-shrink-0">
          <div className="flex items-start justify-between gap-4">
              <h2 className="text-3xl font-bold font-headline text-primary flex-1">{title}</h2>
              <Button variant="ghost" size="icon" onClick={handleGenerateTitle} disabled={isTitleLoading}>
                  {isTitleLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
              </Button>
          </div>
          <div className="flex items-center gap-2 mt-4 mb-2">
            <Button variant="ghost" size="sm" onClick={() => setIsEditing(!isEditing)}><Edit className="h-4 w-4 mr-2"/> {isEditing ? "View" : "Edit"}</Button>
            <Button variant="ghost" size="sm" onClick={handleFetchInsights}>
                {isInsightsLoading ? <Loader2 className="h-4 w-4 animate-spin mr-2"/> : <Sparkles className="h-4 w-4 mr-2"/>}
                {showInsights ? "Hide Insights" : "AI Insights"}
            </Button>
          </div>
        </div>

        <div className="flex-grow min-h-0 overflow-y-auto pr-2">
          {isEditing ? (
            <Textarea 
                value={poem} 
                onChange={(e) => setPoem(e.target.value)} 
                className="w-full h-full text-base leading-relaxed bg-transparent border-2 border-dashed font-serif" 
                rows={poem.split('\n').length + 1}
            />
          ) : (
            showInsights ? (
              <AiInsights insights={insights} isLoading={isInsightsLoading} />
            ) : (
              <div className="whitespace-pre-wrap text-base leading-relaxed font-serif space-y-2">
                {poem.split('\n').map((line, index) => (
                  <PoemLine 
                    key={`${index}-${line}`} 
                    lineNumber={index} 
                    lineText={line}
                    fullPoem={poem}
                    onRewrite={updatePoemLine}
                    />
                ))}
              </div>
            )
          )}
        </div>
        
        <div className="flex-shrink-0 flex items-center gap-2 pt-4 mt-auto">
          <Button onClick={handleSave}><Save className="mr-2 h-4 w-4"/> Save to Library</Button>
          <Button variant="outline" onClick={handleCopy}><Clipboard className="mr-2 h-4 w-4"/> Copy</Button>
          <Button variant="outline" onClick={handleShare}><Share2 className="mr-2 h-4 w-4"/> Share</Button>
          <Button variant="outline" onClick={handleDownload}><Download className="mr-2 h-4 w-4"/> Download</Button>
        </div>
      </div>
    </div>
  );
}
