"use client"

import { useState, useEffect } from "react"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { useToast } from "@/hooks/use-toast"
import { generatePoemTitle } from "@/ai/flows/generate-poem-title"
import { providePoemInspirationInsights } from "@/ai/flows/provide-poem-inspiration-insights"
import {
  Clipboard,
  Download,
  Edit,
  Loader2,
  RefreshCw,
  Save,
  Share2,
  Sparkles,
  Wand2,
  MoreHorizontal,
} from "lucide-react"
import type { GeneratePoemFromImageOutput } from "@/ai/flows/generate-poem-from-image"
import type { PoemInspirationInsightsOutput } from "@/ai/flows/provide-poem-inspiration-insights"
import AiInsights from "./AiInsights"
import PoemLine from "./PoemLine"
import { useLibrary } from "@/context/LibraryContext"
import type { CreativeControlsState } from "./VersifyClient"
import { Badge } from "../ui/badge"
import { useSupabaseUser } from "@/hooks/use-supabase-user"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"

interface PoemDisplayProps {
  poemResult: GeneratePoemFromImageOutput
  image: string
  onRegenerate: () => void
  isRegenerating: boolean
  controls: CreativeControlsState
}

/**
 * Discord-style poem display component with message-like layout.
 */
export default function PoemDisplay({ poemResult, image, onRegenerate, isRegenerating, controls }: PoemDisplayProps) {
  const [title, setTitle] = useState(poemResult.title)
  const [poem, setPoem] = useState(poemResult.poem)
  const [isEditing, setIsEditing] = useState(false)
  const [isTitleLoading, setIsTitleLoading] = useState(false)
  const [showInsights, setShowInsights] = useState(false)
  const [insights, setInsights] = useState<PoemInspirationInsightsOutput | null>(null)
  const [isInsightsLoading, setIsInsightsLoading] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const { toast } = useToast()
  const { addPoemToLibrary } = useLibrary()
  const { user, userLoading } = useSupabaseUser()

  useEffect(() => {
    setTitle(poemResult.title)
    setPoem(poemResult.poem)
    setShowInsights(false)
    setInsights(null)
  }, [poemResult])

  const handleGenerateTitle = async () => {
    setIsTitleLoading(true)
    try {
      const { title: newTitle } = await generatePoemTitle({ poem })
      setTitle(newTitle)
      toast({ title: "New title generated!" })
    } catch (error) {
      toast({ title: "Error generating title", variant: "destructive" })
    } finally {
      setIsTitleLoading(false)
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(`${title}\n\n${poem}`)
    toast({ title: "Poem copied to clipboard!" })
  }

  const handleShare = async () => {
    const shareData = {
      title: `Poem: ${title}`,
      text: `${title}\n\n${poem}\n\n- Generated by Versify`,
    }
    try {
      if (navigator.share) {
        await navigator.share(shareData)
      } else {
        handleCopy()
      }
    } catch (err) {
      console.error("Share failed:", err)
      handleCopy()
    }
  }

  const handleDownload = () => {
    const blob = new Blob([`${title}\n\n${poem}`], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${title.toLowerCase().replace(/\s/g, "_")}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast({ title: "Poem downloaded." })
  }

  const handleFetchInsights = async () => {
    setShowInsights(!showInsights)
    if (!insights && !showInsights) {
      setIsInsightsLoading(true)
      try {
        const insightsResult = await providePoemInspirationInsights({ photoDataUri: image, poem })
        setInsights(insightsResult)
      } catch (error) {
        toast({ title: "Could not get AI insights.", variant: "destructive" })
      } finally {
        setIsInsightsLoading(false)
      }
    }
  }

  const updatePoemLine = (lineNumber: number, newText: string) => {
    const lines = poem.split("\n")
    lines[lineNumber] = newText
    setPoem(lines.join("\n"))
  }

  const handleSave = async () => {
    if (!user) {
      console.log("[v0] Save failed: No user found in state")
      toast({ title: "Please log in to save poems.", variant: "destructive" })
      return
    }

    setIsSaving(true)
    try {
      const imageToSave = {
        id: `custom-${Date.now()}`,
        imageUrl: image,
        description: "Custom uploaded image",
        imageHint: "",
      }

      console.log("[v0] Attempting to save poem with user ID:", user.id)
      await addPoemToLibrary({ title, poem, image: imageToSave, controls })
      toast({ title: "Saved to your library!" })
    } catch (error) {
      console.error("[v0] Poem saving error:", error)
      toast({ title: "Failed to save poem", variant: "destructive" })
    } finally {
      setIsSaving(false)
    }
  }

  const detectedItems = [
    ...(poemResult.visualElements || []).map((item) => ({ type: "Visual", value: item })),
    ...(poemResult.emotions || []).map((item) => ({ type: "Emotion", value: item })),
  ]

  return (
    <div className="space-y-4">
      {/* Message Header */}
      <div className="flex items-start gap-3">
        <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
          <Sparkles className="w-4 h-4 text-primary" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="font-semibold text-sm">Versify AI</span>
            <span className="text-xs text-muted-foreground">just now</span>
          </div>
          <div className="flex items-center gap-1 mb-2">
            <h3 className="font-semibold text-foreground">{title}</h3>
            <Button
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              onClick={handleGenerateTitle}
              disabled={isTitleLoading}
            >
              {isTitleLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Wand2 className="h-3 w-3" />}
            </Button>
          </div>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="h-6 w-6">
              <MoreHorizontal className="h-3 w-3" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={onRegenerate} disabled={isRegenerating}>
              {isRegenerating ? (
                <Loader2 className="mr-2 h-3 w-3 animate-spin" />
              ) : (
                <RefreshCw className="mr-2 h-3 w-3" />
              )}
              Regenerate
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setIsEditing(!isEditing)}>
              <Edit className="mr-2 h-3 w-3" />
              {isEditing ? "View" : "Edit"}
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleFetchInsights}>
              <Sparkles className="mr-2 h-3 w-3" />
              {showInsights ? "Hide Insights" : "AI Insights"}
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {/* Image */}
      <div className="relative w-full max-w-lg aspect-video rounded-lg overflow-hidden">
        <Image
          src={image || "/placeholder.svg"}
          alt="Poem inspiration"
          fill
          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 400px"
          className="object-cover"
        />
      </div>

      {/* Detected Elements */}
      {detectedItems.length > 0 && !showInsights && (
        <div className="flex flex-wrap gap-1">
          {detectedItems.slice(0, 6).map((item, index) => (
            <Badge key={index} variant="secondary" className="text-xs">
              {item.value}
            </Badge>
          ))}
          {detectedItems.length > 6 && (
            <Badge variant="outline" className="text-xs">
              +{detectedItems.length - 6} more
            </Badge>
          )}
        </div>
      )}

      {/* Poem Content */}
      <div className="bg-muted/30 rounded-lg p-4">
        {isEditing ? (
          <Textarea
            value={poem}
            onChange={(e) => setPoem(e.target.value)}
            className="w-full min-h-[200px] text-sm leading-relaxed bg-transparent border-none resize-none focus:ring-0"
            placeholder="Edit your poem..."
          />
        ) : showInsights ? (
          <AiInsights insights={insights} isLoading={isInsightsLoading} />
        ) : (
          <div className="whitespace-pre-wrap text-sm leading-relaxed space-y-1">
            {poem.split("\n").map((line, index) => (
              <PoemLine
                key={`${index}-${line}`}
                lineNumber={index}
                lineText={line}
                fullPoem={poem}
                onRewrite={updatePoemLine}
              />
            ))}
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex items-center gap-2 text-xs">
        <Button variant="ghost" size="sm" onClick={handleSave} disabled={isSaving}>
          {isSaving ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : <Save className="mr-1 h-3 w-3" />}
          Save
        </Button>
        <Button variant="ghost" size="sm" onClick={handleCopy}>
          <Clipboard className="mr-1 h-3 w-3" />
          Copy
        </Button>
        <Button variant="ghost" size="sm" onClick={handleShare}>
          <Share2 className="mr-1 h-3 w-3" />
          Share
        </Button>
        <Button variant="ghost" size="sm" onClick={handleDownload}>
          <Download className="mr-1 h-3 w-3" />
          Download
        </Button>
      </div>

      {/* Trial Completion Message for Non-Logged-In Users */}
      {!userLoading && !user && (
        <div className="bg-gradient-to-r from-primary/10 to-accent/10 rounded-lg p-4 border border-primary/20">
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-primary/20 rounded-full flex items-center justify-center flex-shrink-0">
              <Sparkles className="w-4 h-4 text-primary" />
            </div>
            <div className="flex-1">
              <h4 className="font-semibold text-foreground mb-1">🎉 Trial Complete!</h4>
              <p className="text-sm text-muted-foreground mb-3">
                You've used your free poem generation. Sign up to create unlimited poems, save to your library, and
                access advanced features!
              </p>
              <div className="flex gap-2">
                <Button onClick={() => (window.location.href = "/signup")} size="sm" className="text-xs">
                  Sign Up Free
                </Button>
                <Button
                  onClick={() => (window.location.href = "/login")}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                >
                  Already have an account?
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
